// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: api/proto/UrlProto/AntmanUrl.proto

package Antman

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=originalUrl,proto3" json:"originalUrl,omitempty"`
	CustomAlias string `protobuf:"bytes,2,opt,name=customAlias,proto3" json:"customAlias,omitempty"`
}

func (x *ShortUrlRequest) Reset() {
	*x = ShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlRequest) ProtoMessage() {}

func (x *ShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlRequest.ProtoReflect.Descriptor instead.
func (*ShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortUrlRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortUrlRequest) GetCustomAlias() string {
	if x != nil {
		return x.CustomAlias
	}
	return ""
}

type ShortUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success     bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShortUrlKey string `protobuf:"bytes,2,opt,name=shortUrlKey,proto3" json:"shortUrlKey,omitempty"`
}

func (x *ShortUrlResponse) Reset() {
	*x = ShortUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlResponse) ProtoMessage() {}

func (x *ShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlResponse.ProtoReflect.Descriptor instead.
func (*ShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortUrlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShortUrlResponse) GetShortUrlKey() string {
	if x != nil {
		return x.ShortUrlKey
	}
	return ""
}

type DeleteUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
	Ownerid  int32  `protobuf:"varint,2,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
}

func (x *DeleteUrlRequest) Reset() {
	*x = DeleteUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlRequest) ProtoMessage() {}

func (x *DeleteUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlRequest.ProtoReflect.Descriptor instead.
func (*DeleteUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *DeleteUrlRequest) GetOwnerid() int32 {
	if x != nil {
		return x.Ownerid
	}
	return 0
}

type DeleteUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteUrlResponse) Reset() {
	*x = DeleteUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlResponse) ProtoMessage() {}

func (x *DeleteUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlResponse.ProtoReflect.Descriptor instead.
func (*DeleteUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUrlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LongUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *LongUrlRequest) Reset() {
	*x = LongUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlRequest) ProtoMessage() {}

func (x *LongUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlRequest.ProtoReflect.Descriptor instead.
func (*LongUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{4}
}

func (x *LongUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type LongUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LongUrl string `protobuf:"bytes,2,opt,name=LongUrl,proto3" json:"LongUrl,omitempty"`
}

func (x *LongUrlResponse) Reset() {
	*x = LongUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlResponse) ProtoMessage() {}

func (x *LongUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlResponse.ProtoReflect.Descriptor instead.
func (*LongUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP(), []int{5}
}

func (x *LongUrlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LongUrlResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_api_proto_UrlProto_AntmanUrl_proto protoreflect.FileDescriptor

var file_api_proto_UrlProto_AntmanUrl_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x55, 0x72, 0x6c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x41, 0x6e, 0x74, 0x6d, 0x61, 0x6e, 0x55, 0x72, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a,
	0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55,
	0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x4b, 0x65, 0x79, 0x22, 0x48, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2c, 0x0a,
	0x0e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x0f, 0x4c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x6e, 0x67,
	0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x6e, 0x67, 0x55,
	0x72, 0x6c, 0x32, 0xb3, 0x02, 0x0a, 0x0f, 0x41, 0x6e, 0x74, 0x6d, 0x61, 0x6e, 0x55, 0x72, 0x6c,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x5c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x3a, 0x01, 0x2a, 0x12, 0x5d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x72,
	0x6c, 0x12, 0x1b, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x3a, 0x01, 0x2a, 0x12, 0x63, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72,
	0x6c, 0x12, 0x19, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f,
	0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x55,
	0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18,
	0x12, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x2f, 0x7b, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x7d, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x41, 0x6e,
	0x74, 0x6d, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_UrlProto_AntmanUrl_proto_rawDescOnce sync.Once
	file_api_proto_UrlProto_AntmanUrl_proto_rawDescData = file_api_proto_UrlProto_AntmanUrl_proto_rawDesc
)

func file_api_proto_UrlProto_AntmanUrl_proto_rawDescGZIP() []byte {
	file_api_proto_UrlProto_AntmanUrl_proto_rawDescOnce.Do(func() {
		file_api_proto_UrlProto_AntmanUrl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_UrlProto_AntmanUrl_proto_rawDescData)
	})
	return file_api_proto_UrlProto_AntmanUrl_proto_rawDescData
}

var file_api_proto_UrlProto_AntmanUrl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_UrlProto_AntmanUrl_proto_goTypes = []interface{}{
	(*ShortUrlRequest)(nil),   // 0: UrlServer.ShortUrlRequest
	(*ShortUrlResponse)(nil),  // 1: UrlServer.ShortUrlResponse
	(*DeleteUrlRequest)(nil),  // 2: UrlServer.DeleteUrlRequest
	(*DeleteUrlResponse)(nil), // 3: UrlServer.DeleteUrlResponse
	(*LongUrlRequest)(nil),    // 4: UrlServer.LongUrlRequest
	(*LongUrlResponse)(nil),   // 5: UrlServer.LongUrlResponse
}
var file_api_proto_UrlProto_AntmanUrl_proto_depIdxs = []int32{
	0, // 0: UrlServer.AntmanUrlRoutes.GetShortUrl:input_type -> UrlServer.ShortUrlRequest
	2, // 1: UrlServer.AntmanUrlRoutes.DeleteUrl:input_type -> UrlServer.DeleteUrlRequest
	4, // 2: UrlServer.AntmanUrlRoutes.GetLongUrl:input_type -> UrlServer.LongUrlRequest
	1, // 3: UrlServer.AntmanUrlRoutes.GetShortUrl:output_type -> UrlServer.ShortUrlResponse
	3, // 4: UrlServer.AntmanUrlRoutes.DeleteUrl:output_type -> UrlServer.DeleteUrlResponse
	5, // 5: UrlServer.AntmanUrlRoutes.GetLongUrl:output_type -> UrlServer.LongUrlResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_UrlProto_AntmanUrl_proto_init() }
func file_api_proto_UrlProto_AntmanUrl_proto_init() {
	if File_api_proto_UrlProto_AntmanUrl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_UrlProto_AntmanUrl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_UrlProto_AntmanUrl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_UrlProto_AntmanUrl_proto_goTypes,
		DependencyIndexes: file_api_proto_UrlProto_AntmanUrl_proto_depIdxs,
		MessageInfos:      file_api_proto_UrlProto_AntmanUrl_proto_msgTypes,
	}.Build()
	File_api_proto_UrlProto_AntmanUrl_proto = out.File
	file_api_proto_UrlProto_AntmanUrl_proto_rawDesc = nil
	file_api_proto_UrlProto_AntmanUrl_proto_goTypes = nil
	file_api_proto_UrlProto_AntmanUrl_proto_depIdxs = nil
}
